# Generated by Django 2.2.4 on 2022-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20220628_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='cat',
            field=models.CharField(default='all', max_length=255),
        ),
    ]
